# RPCS3's per-game settings database, compiled into the core. Standalone RPCS3's
# release CI downloads it into GuiConfigs/config_database.dat; a libretro core
# may not download anything at run time, so it is fetched here, when the build
# is configured, and carried in the core (see install_config_database in
# libretro_core.cpp). Without network access the core is built without it, and
# the Database Settings Override option has nothing to apply.
function(libretro_embed_config_database out_file)
    set(db "${CMAKE_CURRENT_BINARY_DIR}/config_database.dat")
    if(NOT EXISTS "${db}")
        file(DOWNLOAD "https://api.rpcs3.net/config/?api=v1" "${db}.part"
            TIMEOUT 60 STATUS status)
        list(GET status 0 code)
        if(code EQUAL 0)
            file(RENAME "${db}.part" "${db}")
        else()
            message(WARNING "config database not downloaded (${status}); the core is built without it")
            file(REMOVE "${db}.part")
        endif()
    endif()
    set(bytes "")
    set(size 0)
    if(EXISTS "${db}")
        file(READ "${db}" hex HEX)
        string(LENGTH "${hex}" hex_len)
        math(EXPR size "${hex_len} / 2")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    endif()
    file(WRITE "${out_file}.tmp"
        "// Generated by embed_config_database.cmake from api.rpcs3.net/config\n"
        "#include <cstddef>\n\n"
        "extern const unsigned char g_libretro_config_database[] = {${bytes}0};\n"
        "extern const std::size_t g_libretro_config_database_size = ${size};\n")
    file(COPY_FILE "${out_file}.tmp" "${out_file}" ONLY_IF_DIFFERENT)
endfunction()
