# RPCS3's per-game settings database, compiled into the core and written to
# GuiConfigs/config_database.dat (install_config_database in libretro_core.cpp).
# Standalone RPCS3's release CI downloads the current one; this core keeps the
# copy next to this file instead, taken from api.rpcs3.net/config/?api=v1.
# Its entries go with the RPCS3 code they were made for - newer ones may rely
# on accuracy fixes or settings this code does not have - so it is replaced
# only together with a merge of upstream RPCS3, not on its own (NNshi).
function(libretro_embed_config_database out_file)
    set(db "${CMAKE_CURRENT_SOURCE_DIR}/config_database.dat")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${db}")
    file(READ "${db}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR size "${hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    file(WRITE "${out_file}.tmp"
        "// Generated by embed_config_database.cmake from config_database.dat\n"
        "#include <cstddef>\n\n"
        "extern const unsigned char g_libretro_config_database[] = {${bytes}0};\n"
        "extern const std::size_t g_libretro_config_database_size = ${size};\n")
    file(COPY_FILE "${out_file}.tmp" "${out_file}" ONLY_IF_DIFFERENT)
endfunction()
