# RPCS3's game patches, patch.yml, compiled into the core and written to
# patches/patch.yml in the config dir (install_patches in libretro_core.cpp).
# Standalone RPCS3 downloads it from its server at run time, from the patch
# manager; a libretro core may not download anything at run time, so it is
# fetched here, each time the build is configured, from the same server and
# for the patch engine version of this code (Utilities/bin_patch.h). Unlike
# config_database.dat it is kept current: patches are versioned for the patch
# engine, not for the emulator (NNshi). github.com/illusionyy/rpcs3-game-patch,
# a mirror of the server's file, stands in when the server cannot be reached;
# without either the core is built without it.
function(libretro_embed_patches out_file)
    file(STRINGS "${CMAKE_SOURCE_DIR}/Utilities/bin_patch.h" version_line REGEX "patch_engine_version = \"[0-9.]+\"")
    string(REGEX REPLACE ".*\"([0-9.]+)\".*" "\\1" version "${version_line}")
    set(patch "")

    file(DOWNLOAD "https://rpcs3.net/compatibility?patch&api=v1&v=${version}" "${CMAKE_CURRENT_BINARY_DIR}/patch.json"
        TIMEOUT 60 STATUS status)
    list(GET status 0 code)
    if(code EQUAL 0)
        file(READ "${CMAKE_CURRENT_BINARY_DIR}/patch.json" json)
        string(JSON return_code ERROR_VARIABLE error GET "${json}" return_code)
        string(JSON patch ERROR_VARIABLE error GET "${json}" patch)
        string(JSON sha256 ERROR_VARIABLE error GET "${json}" sha256)
        if(error OR NOT return_code EQUAL 0)
            set(patch "")
        else()
            string(SHA256 actual "${patch}")
            if(NOT actual STREQUAL sha256)
                message(WARNING "patch.yml from rpcs3.net does not match its sha256")
                set(patch "")
            endif()
        endif()
    endif()
    if(patch STREQUAL "")
        file(DOWNLOAD "https://raw.githubusercontent.com/illusionyy/rpcs3-game-patch/main/patch.yml"
            "${CMAKE_CURRENT_BINARY_DIR}/patch.yml.part" TIMEOUT 60 STATUS status)
        list(GET status 0 code)
        if(code EQUAL 0)
            file(READ "${CMAKE_CURRENT_BINARY_DIR}/patch.yml.part" patch)
            if(NOT patch MATCHES "^Version: ${version}")
                set(patch "")
            endif()
        endif()
    endif()
    if(patch STREQUAL "")
        message(WARNING "patch.yml not downloaded; the core is built without it")
    else()
        message(STATUS "patch.yml for patch engine ${version} embedded")
    endif()

    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/patch.yml" "${patch}")
    file(READ "${CMAKE_CURRENT_BINARY_DIR}/patch.yml" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR size "${hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    file(WRITE "${out_file}.tmp"
        "// Generated by embed_patches.cmake from rpcs3.net's patch.yml\n"
        "#include <cstddef>\n\n"
        "extern const unsigned char g_libretro_patch_yml[] = {${bytes}0};\n"
        "extern const std::size_t g_libretro_patch_yml_size = ${size};\n")
    file(COPY_FILE "${out_file}.tmp" "${out_file}" ONLY_IF_DIFFERENT)
endfunction()
