# Compiles bin/Icons/ui into the core. RPCS3's in-game overlays (message and
# save data dialogs, the on-screen keyboard) draw these, and standalone RPCS3
# ships them next to the executable - a core is a single file, so it carries
# them itself and installs them into the config dir (libretro_ui_icons.h).
function(libretro_embed_ui_icons out_file)
    file(GLOB icons CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/bin/Icons/ui/*.png")
    list(SORT icons)
    set(data "")
    set(table "")
    set(index 0)
    foreach(icon IN LISTS icons)
        get_filename_component(name "${icon}" NAME)
        file(READ "${icon}" hex HEX)
        string(LENGTH "${hex}" hex_len)
        math(EXPR size "${hex_len} / 2")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
        string(APPEND data "static const unsigned char icon_${index}[] = {${bytes}};\n")
        string(APPEND table "    {\"${name}\", icon_${index}, ${size}},\n")
        math(EXPR index "${index} + 1")
    endforeach()
    file(WRITE "${out_file}.tmp"
        "// Generated by embed_ui_icons.cmake from bin/Icons/ui\n"
        "#include \"libretro_ui_icons.h\"\n\n"
        "${data}\n"
        "const libretro_ui_icon g_libretro_ui_icons[] = {\n${table}};\n"
        "const std::size_t g_libretro_ui_icon_count = ${index};\n")
    file(COPY_FILE "${out_file}.tmp" "${out_file}" ONLY_IF_DIFFERENT)
endfunction()
