#!/usr/bin/env python3
"""Generate libretro_localized_strings.h from upstream's rpcs3qt/localized_emu.h.

The emulator asks for every text it shows (progress, save and message dialogs,
trophies, the home menu) through get_localized_string. Standalone answers from
rpcs3qt/localized_emu.h, which is Qt and not part of this repository, and the
core used to answer with an empty string. This turns its English strings into a
plain table. Run it after merging upstream:

    python3 rpcs3/libretro/gen_localized_strings.py [git-ref]

git-ref is the upstream commit to read the file from (default: the commit in
upstream.version).
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'libretro_localized_strings.h')

def upstream_commit():
    with open(os.path.join(HERE, 'upstream.version'), encoding='utf-8') as f:
        for line in f:
            if line.startswith('RPCS3_COMMIT='):
                return line.split('=', 1)[1].strip()
    sys.exit('upstream.version has no RPCS3_COMMIT')

ref = sys.argv[1] if len(sys.argv) > 1 else upstream_commit()
src = subprocess.run(['git', 'show', f'{ref}:rpcs3/rpcs3qt/localized_emu.h'], cwd=HERE,
                     check=True, capture_output=True).stdout.decode('utf-8')

literal = r'"((?:[^"\\]|\\.)*)"'
case = re.compile(r'case localized_string_id::(\w+):\s*return\s+(?:tr\(\s*' + literal + r'(?:\s*,\s*' + literal + r')?\s*\)|' + literal + r')')

entries = []
for line in src.splitlines():
    if 'case localized_string_id::' not in line:
        continue
    m = case.search(line)
    if not m:
        sys.exit(f'cannot parse: {line.strip()}')
    text = m.group(2) if m.group(2) is not None else m.group(4)
    entries.append((m.group(1), text))

with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by gen_localized_strings.py from upstream rpcs3qt/localized_emu.h\n')
    f.write(f'// ({ref}). Do not edit; run the script again after an upstream merge.\n\n')
    f.write('#pragma once\n\n#include "Emu/localized_string_id.h"\n\n')
    f.write('// English text for an id, with %0 where standalone inserts its argument;\n')
    f.write('// nullptr for an id this table does not know.\n')
    f.write('inline const char* libretro_localized_template(localized_string_id id)\n{\n\tswitch (id)\n\t{\n')
    for name, text in entries:
        f.write(f'\tcase localized_string_id::{name}: return "{text}";\n')
    f.write('\tdefault: return nullptr;\n\t}\n}\n')

print(f'{len(entries)} strings -> {os.path.relpath(OUT)}')
